replaceitem entity @s[scores={aestd.block_id=0}] weapon minecraft:air
replaceitem entity @s[scores={aestd.block_id=1}] weapon minecraft:stone
replaceitem entity @s[scores={aestd.block_id=2}] weapon minecraft:granite
replaceitem entity @s[scores={aestd.block_id=3}] weapon minecraft:polished_granite
replaceitem entity @s[scores={aestd.block_id=4}] weapon minecraft:diorite
replaceitem entity @s[scores={aestd.block_id=5}] weapon minecraft:polished_diorite
replaceitem entity @s[scores={aestd.block_id=6}] weapon minecraft:andesite
replaceitem entity @s[scores={aestd.block_id=7}] weapon minecraft:polished_andesite
replaceitem entity @s[scores={aestd.block_id=8}] weapon minecraft:grass_block
replaceitem entity @s[scores={aestd.block_id=9}] weapon minecraft:dirt
