replaceitem entity @s[scores={aestd.block_id=10}] weapon minecraft:coarse_dirt
replaceitem entity @s[scores={aestd.block_id=11}] weapon minecraft:podzol
replaceitem entity @s[scores={aestd.block_id=12}] weapon minecraft:cobblestone
replaceitem entity @s[scores={aestd.block_id=13}] weapon minecraft:oak_planks
replaceitem entity @s[scores={aestd.block_id=14}] weapon minecraft:spruce_planks
replaceitem entity @s[scores={aestd.block_id=15}] weapon minecraft:birch_planks
replaceitem entity @s[scores={aestd.block_id=16}] weapon minecraft:jungle_planks
replaceitem entity @s[scores={aestd.block_id=17}] weapon minecraft:acacia_planks
replaceitem entity @s[scores={aestd.block_id=18}] weapon minecraft:dark_oak_planks
replaceitem entity @s[scores={aestd.block_id=19}] weapon minecraft:oak_sapling
replaceitem entity @s[scores={aestd.block_id=20}] weapon minecraft:spruce_sapling
