replaceitem entity @s[scores={aestd.block_id=31}] weapon minecraft:gold_ore
replaceitem entity @s[scores={aestd.block_id=32}] weapon minecraft:iron_ore
replaceitem entity @s[scores={aestd.block_id=33}] weapon minecraft:coal_ore
replaceitem entity @s[scores={aestd.block_id=34}] weapon minecraft:oak_log
replaceitem entity @s[scores={aestd.block_id=35}] weapon minecraft:spruce_log
replaceitem entity @s[scores={aestd.block_id=36}] weapon minecraft:birch_log
replaceitem entity @s[scores={aestd.block_id=37}] weapon minecraft:jungle_log
replaceitem entity @s[scores={aestd.block_id=38}] weapon minecraft:acacia_log
replaceitem entity @s[scores={aestd.block_id=39}] weapon minecraft:dark_oak_log
replaceitem entity @s[scores={aestd.block_id=40}] weapon minecraft:stripped_spruce_log
replaceitem entity @s[scores={aestd.block_id=41}] weapon minecraft:stripped_birch_log
