replaceitem entity @s[scores={aestd.block_id=42}] weapon minecraft:stripped_jungle_log
replaceitem entity @s[scores={aestd.block_id=43}] weapon minecraft:stripped_acacia_log
replaceitem entity @s[scores={aestd.block_id=44}] weapon minecraft:stripped_dark_oak_log
replaceitem entity @s[scores={aestd.block_id=45}] weapon minecraft:stripped_oak_log
replaceitem entity @s[scores={aestd.block_id=46}] weapon minecraft:oak_wood
replaceitem entity @s[scores={aestd.block_id=47}] weapon minecraft:spruce_wood
replaceitem entity @s[scores={aestd.block_id=48}] weapon minecraft:birch_wood
replaceitem entity @s[scores={aestd.block_id=49}] weapon minecraft:jungle_wood
replaceitem entity @s[scores={aestd.block_id=50}] weapon minecraft:acacia_wood
replaceitem entity @s[scores={aestd.block_id=51}] weapon minecraft:dark_oak_wood
