replaceitem entity @s[scores={aestd.block_id=52}] weapon minecraft:stripped_oak_wood
replaceitem entity @s[scores={aestd.block_id=53}] weapon minecraft:stripped_spruce_wood
replaceitem entity @s[scores={aestd.block_id=54}] weapon minecraft:stripped_birch_wood
replaceitem entity @s[scores={aestd.block_id=55}] weapon minecraft:stripped_jungle_wood
replaceitem entity @s[scores={aestd.block_id=56}] weapon minecraft:stripped_acacia_wood
replaceitem entity @s[scores={aestd.block_id=57}] weapon minecraft:stripped_dark_oak_wood
replaceitem entity @s[scores={aestd.block_id=58}] weapon minecraft:oak_leaves
replaceitem entity @s[scores={aestd.block_id=59}] weapon minecraft:spruce_leaves
replaceitem entity @s[scores={aestd.block_id=60}] weapon minecraft:birch_leaves
replaceitem entity @s[scores={aestd.block_id=61}] weapon minecraft:jungle_leaves
replaceitem entity @s[scores={aestd.block_id=62}] weapon minecraft:acacia_leaves
