replaceitem entity @s[scores={aestd.block_id=73}] weapon minecraft:note_block
replaceitem entity @s[scores={aestd.block_id=74}] weapon minecraft:white_bed
replaceitem entity @s[scores={aestd.block_id=75}] weapon minecraft:orange_bed
replaceitem entity @s[scores={aestd.block_id=76}] weapon minecraft:magenta_bed
replaceitem entity @s[scores={aestd.block_id=77}] weapon minecraft:light_blue_bed
replaceitem entity @s[scores={aestd.block_id=78}] weapon minecraft:yellow_bed
replaceitem entity @s[scores={aestd.block_id=79}] weapon minecraft:lime_bed
replaceitem entity @s[scores={aestd.block_id=80}] weapon minecraft:pink_bed
replaceitem entity @s[scores={aestd.block_id=81}] weapon minecraft:gray_bed
replaceitem entity @s[scores={aestd.block_id=82}] weapon minecraft:light_gray_bed
replaceitem entity @s[scores={aestd.block_id=83}] weapon minecraft:cyan_bed
