replaceitem entity @s[scores={aestd.block_id=84}] weapon minecraft:purple_bed
replaceitem entity @s[scores={aestd.block_id=85}] weapon minecraft:blue_bed
replaceitem entity @s[scores={aestd.block_id=86}] weapon minecraft:brown_bed
replaceitem entity @s[scores={aestd.block_id=87}] weapon minecraft:green_bed
replaceitem entity @s[scores={aestd.block_id=88}] weapon minecraft:red_bed
replaceitem entity @s[scores={aestd.block_id=89}] weapon minecraft:black_bed
replaceitem entity @s[scores={aestd.block_id=90}] weapon minecraft:powered_rail
replaceitem entity @s[scores={aestd.block_id=91}] weapon minecraft:detector_rail
replaceitem entity @s[scores={aestd.block_id=92}] weapon minecraft:sticky_piston
replaceitem entity @s[scores={aestd.block_id=93}] weapon minecraft:cobweb
