replaceitem entity @s[scores={aestd.block_id=115}] weapon minecraft:red_wool
replaceitem entity @s[scores={aestd.block_id=116}] weapon minecraft:black_wool
replaceitem entity @s[scores={aestd.block_id=118}] weapon minecraft:dandelion
replaceitem entity @s[scores={aestd.block_id=119}] weapon minecraft:poppy
replaceitem entity @s[scores={aestd.block_id=120}] weapon minecraft:blue_orchid
replaceitem entity @s[scores={aestd.block_id=121}] weapon minecraft:allium
replaceitem entity @s[scores={aestd.block_id=122}] weapon minecraft:azure_bluet
replaceitem entity @s[scores={aestd.block_id=123}] weapon minecraft:red_tulip
replaceitem entity @s[scores={aestd.block_id=124}] weapon minecraft:orange_tulip
replaceitem entity @s[scores={aestd.block_id=125}] weapon minecraft:white_tulip
