replaceitem entity @s[scores={aestd.block_id=178}] weapon minecraft:redstone_ore
replaceitem entity @s[scores={aestd.block_id=179}] weapon minecraft:redstone_torch
replaceitem entity @s[scores={aestd.block_id=180}] weapon minecraft:redstone_torch
replaceitem entity @s[scores={aestd.block_id=181}] weapon minecraft:stone_button
replaceitem entity @s[scores={aestd.block_id=182}] weapon minecraft:snow
replaceitem entity @s[scores={aestd.block_id=183}] weapon minecraft:ice
replaceitem entity @s[scores={aestd.block_id=184}] weapon minecraft:snow_block
replaceitem entity @s[scores={aestd.block_id=185}] weapon minecraft:cactus
replaceitem entity @s[scores={aestd.block_id=186}] weapon minecraft:clay
replaceitem entity @s[scores={aestd.block_id=187}] weapon minecraft:sugar_cane
replaceitem entity @s[scores={aestd.block_id=188}] weapon minecraft:jukebox
