replaceitem entity @s[scores={aestd.block_id=199}] weapon minecraft:white_stained_glass
replaceitem entity @s[scores={aestd.block_id=200}] weapon minecraft:orange_stained_glass
replaceitem entity @s[scores={aestd.block_id=201}] weapon minecraft:magenta_stained_glass
replaceitem entity @s[scores={aestd.block_id=202}] weapon minecraft:light_blue_stained_glass
replaceitem entity @s[scores={aestd.block_id=203}] weapon minecraft:yellow_stained_glass
replaceitem entity @s[scores={aestd.block_id=204}] weapon minecraft:lime_stained_glass
replaceitem entity @s[scores={aestd.block_id=205}] weapon minecraft:pink_stained_glass
replaceitem entity @s[scores={aestd.block_id=206}] weapon minecraft:gray_stained_glass
replaceitem entity @s[scores={aestd.block_id=207}] weapon minecraft:light_gray_stained_glass
replaceitem entity @s[scores={aestd.block_id=208}] weapon minecraft:cyan_stained_glass
replaceitem entity @s[scores={aestd.block_id=209}] weapon minecraft:purple_stained_glass
