replaceitem entity @s[scores={aestd.block_id=220}] weapon minecraft:dark_oak_trapdoor
replaceitem entity @s[scores={aestd.block_id=221}] weapon minecraft:stone_bricks
replaceitem entity @s[scores={aestd.block_id=222}] weapon minecraft:mossy_stone_bricks
replaceitem entity @s[scores={aestd.block_id=223}] weapon minecraft:cracked_stone_bricks
replaceitem entity @s[scores={aestd.block_id=224}] weapon minecraft:chiseled_stone_bricks
replaceitem entity @s[scores={aestd.block_id=225}] weapon minecraft:infested_stone
replaceitem entity @s[scores={aestd.block_id=226}] weapon minecraft:infested_cobblestone
replaceitem entity @s[scores={aestd.block_id=227}] weapon minecraft:infested_stone_bricks
replaceitem entity @s[scores={aestd.block_id=228}] weapon minecraft:infested_mossy_stone_bricks
replaceitem entity @s[scores={aestd.block_id=229}] weapon minecraft:infested_cracked_stone_bricks
replaceitem entity @s[scores={aestd.block_id=230}] weapon minecraft:infested_chiseled_stone_bricks
