replaceitem entity @s[scores={aestd.block_id=231}] weapon minecraft:brown_mushroom_block
replaceitem entity @s[scores={aestd.block_id=232}] weapon minecraft:red_mushroom_block
replaceitem entity @s[scores={aestd.block_id=233}] weapon minecraft:mushroom_stem
replaceitem entity @s[scores={aestd.block_id=234}] weapon minecraft:iron_bars
replaceitem entity @s[scores={aestd.block_id=235}] weapon minecraft:glass_pane
replaceitem entity @s[scores={aestd.block_id=236}] weapon minecraft:melon
replaceitem entity @s[scores={aestd.block_id=237}] weapon minecraft:pumpkin_seeds
replaceitem entity @s[scores={aestd.block_id=238}] weapon minecraft:melon_seeds
replaceitem entity @s[scores={aestd.block_id=239}] weapon minecraft:pumpkin_seeds
replaceitem entity @s[scores={aestd.block_id=240}] weapon minecraft:melon_seeds
