replaceitem entity @s[scores={aestd.block_id=241}] weapon minecraft:vine
replaceitem entity @s[scores={aestd.block_id=242}] weapon minecraft:oak_fence_gate
replaceitem entity @s[scores={aestd.block_id=243}] weapon minecraft:brick_stairs
replaceitem entity @s[scores={aestd.block_id=244}] weapon minecraft:stone_brick_stairs
replaceitem entity @s[scores={aestd.block_id=245}] weapon minecraft:mycelium
replaceitem entity @s[scores={aestd.block_id=246}] weapon minecraft:lily_pad
replaceitem entity @s[scores={aestd.block_id=247}] weapon minecraft:nether_bricks
replaceitem entity @s[scores={aestd.block_id=248}] weapon minecraft:nether_brick_fence
replaceitem entity @s[scores={aestd.block_id=249}] weapon minecraft:nether_brick_stairs
replaceitem entity @s[scores={aestd.block_id=250}] weapon minecraft:nether_wart
replaceitem entity @s[scores={aestd.block_id=251}] weapon minecraft:enchanting_table
