replaceitem entity @s[scores={aestd.block_id=273}] weapon minecraft:flower_pot
replaceitem entity @s[scores={aestd.block_id=274}] weapon minecraft:oak_sapling
replaceitem entity @s[scores={aestd.block_id=275}] weapon minecraft:spruce_sapling
replaceitem entity @s[scores={aestd.block_id=276}] weapon minecraft:birch_sapling
replaceitem entity @s[scores={aestd.block_id=277}] weapon minecraft:jungle_sapling
replaceitem entity @s[scores={aestd.block_id=278}] weapon minecraft:acacia_sapling
replaceitem entity @s[scores={aestd.block_id=279}] weapon minecraft:dark_oak_sapling
replaceitem entity @s[scores={aestd.block_id=280}] weapon minecraft:fern
replaceitem entity @s[scores={aestd.block_id=281}] weapon minecraft:dandelion
replaceitem entity @s[scores={aestd.block_id=282}] weapon minecraft:poppy
