replaceitem entity @s[scores={aestd.block_id=294}] weapon minecraft:red_mushroom
replaceitem entity @s[scores={aestd.block_id=295}] weapon minecraft:brown_mushroom
replaceitem entity @s[scores={aestd.block_id=296}] weapon minecraft:dead_bush
replaceitem entity @s[scores={aestd.block_id=297}] weapon minecraft:cactus
replaceitem entity @s[scores={aestd.block_id=298}] weapon minecraft:carrot
replaceitem entity @s[scores={aestd.block_id=299}] weapon minecraft:potato
replaceitem entity @s[scores={aestd.block_id=300}] weapon minecraft:oak_button
replaceitem entity @s[scores={aestd.block_id=301}] weapon minecraft:spruce_button
replaceitem entity @s[scores={aestd.block_id=302}] weapon minecraft:birch_button
replaceitem entity @s[scores={aestd.block_id=303}] weapon minecraft:jungle_button
