replaceitem entity @s[scores={aestd.block_id=325}] weapon minecraft:daylight_detector
replaceitem entity @s[scores={aestd.block_id=326}] weapon minecraft:redstone_block
replaceitem entity @s[scores={aestd.block_id=327}] weapon minecraft:nether_quartz_ore
replaceitem entity @s[scores={aestd.block_id=328}] weapon minecraft:hopper
replaceitem entity @s[scores={aestd.block_id=329}] weapon minecraft:quartz_block
replaceitem entity @s[scores={aestd.block_id=330}] weapon minecraft:chiseled_quartz_block
replaceitem entity @s[scores={aestd.block_id=331}] weapon minecraft:quartz_pillar
replaceitem entity @s[scores={aestd.block_id=332}] weapon minecraft:quartz_stairs
replaceitem entity @s[scores={aestd.block_id=333}] weapon minecraft:activator_rail
replaceitem entity @s[scores={aestd.block_id=334}] weapon minecraft:dropper
replaceitem entity @s[scores={aestd.block_id=335}] weapon minecraft:white_terracotta
