replaceitem entity @s[scores={aestd.block_id=346}] weapon minecraft:blue_terracotta
replaceitem entity @s[scores={aestd.block_id=347}] weapon minecraft:brown_terracotta
replaceitem entity @s[scores={aestd.block_id=348}] weapon minecraft:green_terracotta
replaceitem entity @s[scores={aestd.block_id=349}] weapon minecraft:red_terracotta
replaceitem entity @s[scores={aestd.block_id=350}] weapon minecraft:black_terracotta
replaceitem entity @s[scores={aestd.block_id=351}] weapon minecraft:white_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=352}] weapon minecraft:orange_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=353}] weapon minecraft:magenta_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=354}] weapon minecraft:light_blue_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=355}] weapon minecraft:yellow_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=356}] weapon minecraft:lime_stained_glass_pane
