replaceitem entity @s[scores={aestd.block_id=357}] weapon minecraft:pink_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=358}] weapon minecraft:gray_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=359}] weapon minecraft:light_gray_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=360}] weapon minecraft:cyan_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=361}] weapon minecraft:purple_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=362}] weapon minecraft:blue_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=363}] weapon minecraft:brown_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=364}] weapon minecraft:green_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=365}] weapon minecraft:red_stained_glass_pane
replaceitem entity @s[scores={aestd.block_id=366}] weapon minecraft:black_stained_glass_pane
