replaceitem entity @s[scores={aestd.block_id=367}] weapon minecraft:acacia_stairs
replaceitem entity @s[scores={aestd.block_id=368}] weapon minecraft:dark_oak_stairs
replaceitem entity @s[scores={aestd.block_id=369}] weapon minecraft:slime_block
replaceitem entity @s[scores={aestd.block_id=370}] weapon minecraft:barrier
replaceitem entity @s[scores={aestd.block_id=371}] weapon minecraft:iron_trapdoor
replaceitem entity @s[scores={aestd.block_id=372}] weapon minecraft:prismarine
replaceitem entity @s[scores={aestd.block_id=373}] weapon minecraft:prismarine_bricks
replaceitem entity @s[scores={aestd.block_id=374}] weapon minecraft:dark_prismarine
replaceitem entity @s[scores={aestd.block_id=375}] weapon minecraft:prismarine_stairs
replaceitem entity @s[scores={aestd.block_id=376}] weapon minecraft:prismarine_brick_stairs
replaceitem entity @s[scores={aestd.block_id=377}] weapon minecraft:dark_prismarine_stairs
