replaceitem entity @s[scores={aestd.block_id=388}] weapon minecraft:lime_carpet
replaceitem entity @s[scores={aestd.block_id=389}] weapon minecraft:pink_carpet
replaceitem entity @s[scores={aestd.block_id=390}] weapon minecraft:gray_carpet
replaceitem entity @s[scores={aestd.block_id=391}] weapon minecraft:light_gray_carpet
replaceitem entity @s[scores={aestd.block_id=392}] weapon minecraft:cyan_carpet
replaceitem entity @s[scores={aestd.block_id=393}] weapon minecraft:purple_carpet
replaceitem entity @s[scores={aestd.block_id=394}] weapon minecraft:blue_carpet
replaceitem entity @s[scores={aestd.block_id=395}] weapon minecraft:brown_carpet
replaceitem entity @s[scores={aestd.block_id=396}] weapon minecraft:green_carpet
replaceitem entity @s[scores={aestd.block_id=397}] weapon minecraft:red_carpet
replaceitem entity @s[scores={aestd.block_id=398}] weapon minecraft:black_carpet
