replaceitem entity @s[scores={aestd.block_id=399}] weapon minecraft:terracotta
replaceitem entity @s[scores={aestd.block_id=400}] weapon minecraft:coal_block
replaceitem entity @s[scores={aestd.block_id=401}] weapon minecraft:packed_ice
replaceitem entity @s[scores={aestd.block_id=402}] weapon minecraft:sunflower
replaceitem entity @s[scores={aestd.block_id=403}] weapon minecraft:lilac
replaceitem entity @s[scores={aestd.block_id=404}] weapon minecraft:rose_bush
replaceitem entity @s[scores={aestd.block_id=405}] weapon minecraft:peony
replaceitem entity @s[scores={aestd.block_id=406}] weapon minecraft:tall_grass
replaceitem entity @s[scores={aestd.block_id=407}] weapon minecraft:large_fern
replaceitem entity @s[scores={aestd.block_id=408}] weapon minecraft:white_banner
