replaceitem entity @s[scores={aestd.block_id=409}] weapon minecraft:orange_banner
replaceitem entity @s[scores={aestd.block_id=410}] weapon minecraft:magenta_banner
replaceitem entity @s[scores={aestd.block_id=411}] weapon minecraft:light_blue_banner
replaceitem entity @s[scores={aestd.block_id=412}] weapon minecraft:yellow_banner
replaceitem entity @s[scores={aestd.block_id=413}] weapon minecraft:lime_banner
replaceitem entity @s[scores={aestd.block_id=414}] weapon minecraft:pink_banner
replaceitem entity @s[scores={aestd.block_id=415}] weapon minecraft:gray_banner
replaceitem entity @s[scores={aestd.block_id=416}] weapon minecraft:light_gray_banner
replaceitem entity @s[scores={aestd.block_id=417}] weapon minecraft:cyan_banner
replaceitem entity @s[scores={aestd.block_id=418}] weapon minecraft:purple_banner
replaceitem entity @s[scores={aestd.block_id=419}] weapon minecraft:blue_banner
