replaceitem entity @s[scores={aestd.block_id=430}] weapon minecraft:pink_banner
replaceitem entity @s[scores={aestd.block_id=431}] weapon minecraft:gray_banner
replaceitem entity @s[scores={aestd.block_id=432}] weapon minecraft:light_gray_banner
replaceitem entity @s[scores={aestd.block_id=433}] weapon minecraft:cyan_banner
replaceitem entity @s[scores={aestd.block_id=434}] weapon minecraft:purple_banner
replaceitem entity @s[scores={aestd.block_id=435}] weapon minecraft:blue_banner
replaceitem entity @s[scores={aestd.block_id=436}] weapon minecraft:brown_banner
replaceitem entity @s[scores={aestd.block_id=437}] weapon minecraft:green_banner
replaceitem entity @s[scores={aestd.block_id=438}] weapon minecraft:red_banner
replaceitem entity @s[scores={aestd.block_id=439}] weapon minecraft:black_banner
replaceitem entity @s[scores={aestd.block_id=440}] weapon minecraft:red_sandstone
