replaceitem entity @s[scores={aestd.block_id=472}] weapon minecraft:jungle_fence
replaceitem entity @s[scores={aestd.block_id=473}] weapon minecraft:acacia_fence
replaceitem entity @s[scores={aestd.block_id=474}] weapon minecraft:dark_oak_fence
replaceitem entity @s[scores={aestd.block_id=475}] weapon minecraft:spruce_door
replaceitem entity @s[scores={aestd.block_id=476}] weapon minecraft:birch_door
replaceitem entity @s[scores={aestd.block_id=477}] weapon minecraft:jungle_door
replaceitem entity @s[scores={aestd.block_id=478}] weapon minecraft:acacia_door
replaceitem entity @s[scores={aestd.block_id=479}] weapon minecraft:dark_oak_door
replaceitem entity @s[scores={aestd.block_id=480}] weapon minecraft:end_rod
replaceitem entity @s[scores={aestd.block_id=481}] weapon minecraft:chorus_plant
replaceitem entity @s[scores={aestd.block_id=482}] weapon minecraft:chorus_flower
