replaceitem entity @s[scores={aestd.block_id=493}] weapon minecraft:magma_block
replaceitem entity @s[scores={aestd.block_id=494}] weapon minecraft:nether_wart_block
replaceitem entity @s[scores={aestd.block_id=495}] weapon minecraft:red_nether_bricks
replaceitem entity @s[scores={aestd.block_id=496}] weapon minecraft:bone_block
replaceitem entity @s[scores={aestd.block_id=497}] weapon minecraft:structure_void
replaceitem entity @s[scores={aestd.block_id=498}] weapon minecraft:observer
replaceitem entity @s[scores={aestd.block_id=499}] weapon minecraft:shulker_box
replaceitem entity @s[scores={aestd.block_id=500}] weapon minecraft:white_shulker_box
replaceitem entity @s[scores={aestd.block_id=501}] weapon minecraft:orange_shulker_box
replaceitem entity @s[scores={aestd.block_id=502}] weapon minecraft:magenta_shulker_box
replaceitem entity @s[scores={aestd.block_id=503}] weapon minecraft:light_blue_shulker_box
