replaceitem entity @s[scores={aestd.block_id=504}] weapon minecraft:yellow_shulker_box
replaceitem entity @s[scores={aestd.block_id=505}] weapon minecraft:lime_shulker_box
replaceitem entity @s[scores={aestd.block_id=506}] weapon minecraft:pink_shulker_box
replaceitem entity @s[scores={aestd.block_id=507}] weapon minecraft:gray_shulker_box
replaceitem entity @s[scores={aestd.block_id=508}] weapon minecraft:light_gray_shulker_box
replaceitem entity @s[scores={aestd.block_id=509}] weapon minecraft:cyan_shulker_box
replaceitem entity @s[scores={aestd.block_id=510}] weapon minecraft:purple_shulker_box
replaceitem entity @s[scores={aestd.block_id=511}] weapon minecraft:blue_shulker_box
replaceitem entity @s[scores={aestd.block_id=512}] weapon minecraft:brown_shulker_box
replaceitem entity @s[scores={aestd.block_id=513}] weapon minecraft:green_shulker_box
