replaceitem entity @s[scores={aestd.block_id=514}] weapon minecraft:red_shulker_box
replaceitem entity @s[scores={aestd.block_id=515}] weapon minecraft:black_shulker_box
replaceitem entity @s[scores={aestd.block_id=516}] weapon minecraft:white_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=517}] weapon minecraft:orange_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=518}] weapon minecraft:magenta_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=519}] weapon minecraft:light_blue_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=520}] weapon minecraft:yellow_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=521}] weapon minecraft:lime_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=522}] weapon minecraft:pink_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=523}] weapon minecraft:gray_glazed_terracotta
replaceitem entity @s[scores={aestd.block_id=524}] weapon minecraft:light_gray_glazed_terracotta
