replaceitem entity @s[scores={aestd.block_id=535}] weapon minecraft:light_blue_concrete
replaceitem entity @s[scores={aestd.block_id=536}] weapon minecraft:yellow_concrete
replaceitem entity @s[scores={aestd.block_id=537}] weapon minecraft:lime_concrete
replaceitem entity @s[scores={aestd.block_id=538}] weapon minecraft:pink_concrete
replaceitem entity @s[scores={aestd.block_id=539}] weapon minecraft:gray_concrete
replaceitem entity @s[scores={aestd.block_id=540}] weapon minecraft:light_gray_concrete
replaceitem entity @s[scores={aestd.block_id=541}] weapon minecraft:cyan_concrete
replaceitem entity @s[scores={aestd.block_id=542}] weapon minecraft:purple_concrete
replaceitem entity @s[scores={aestd.block_id=543}] weapon minecraft:blue_concrete
replaceitem entity @s[scores={aestd.block_id=544}] weapon minecraft:brown_concrete
replaceitem entity @s[scores={aestd.block_id=545}] weapon minecraft:green_concrete
