replaceitem entity @s[scores={aestd.block_id=556}] weapon minecraft:light_gray_concrete_powder
replaceitem entity @s[scores={aestd.block_id=557}] weapon minecraft:cyan_concrete_powder
replaceitem entity @s[scores={aestd.block_id=558}] weapon minecraft:purple_concrete_powder
replaceitem entity @s[scores={aestd.block_id=559}] weapon minecraft:blue_concrete_powder
replaceitem entity @s[scores={aestd.block_id=560}] weapon minecraft:brown_concrete_powder
replaceitem entity @s[scores={aestd.block_id=561}] weapon minecraft:green_concrete_powder
replaceitem entity @s[scores={aestd.block_id=562}] weapon minecraft:red_concrete_powder
replaceitem entity @s[scores={aestd.block_id=563}] weapon minecraft:black_concrete_powder
replaceitem entity @s[scores={aestd.block_id=564}] weapon minecraft:kelp
replaceitem entity @s[scores={aestd.block_id=565}] weapon minecraft:kelp
replaceitem entity @s[scores={aestd.block_id=566}] weapon minecraft:dried_kelp_block
