replaceitem entity @s[scores={aestd.block_id=598}] weapon minecraft:dead_tube_coral_fan
replaceitem entity @s[scores={aestd.block_id=599}] weapon minecraft:dead_brain_coral_fan
replaceitem entity @s[scores={aestd.block_id=600}] weapon minecraft:dead_bubble_coral_fan
replaceitem entity @s[scores={aestd.block_id=601}] weapon minecraft:dead_fire_coral_fan
replaceitem entity @s[scores={aestd.block_id=602}] weapon minecraft:dead_horn_coral_fan
replaceitem entity @s[scores={aestd.block_id=603}] weapon minecraft:tube_coral_fan
replaceitem entity @s[scores={aestd.block_id=604}] weapon minecraft:brain_coral_fan
replaceitem entity @s[scores={aestd.block_id=605}] weapon minecraft:bubble_coral_fan
replaceitem entity @s[scores={aestd.block_id=606}] weapon minecraft:fire_coral_fan
replaceitem entity @s[scores={aestd.block_id=607}] weapon minecraft:horn_coral_fan
replaceitem entity @s[scores={aestd.block_id=608}] weapon minecraft:sea_pickle
