replaceitem entity @s[scores={aestd.block_id=630}] weapon minecraft:diorite_stairs
replaceitem entity @s[scores={aestd.block_id=631}] weapon minecraft:polished_granite_slab
replaceitem entity @s[scores={aestd.block_id=632}] weapon minecraft:smooth_red_sandstone_slab
replaceitem entity @s[scores={aestd.block_id=633}] weapon minecraft:mossy_stone_brick_slab
replaceitem entity @s[scores={aestd.block_id=634}] weapon minecraft:polished_diorite_slab
replaceitem entity @s[scores={aestd.block_id=635}] weapon minecraft:mossy_cobblestone_slab
replaceitem entity @s[scores={aestd.block_id=636}] weapon minecraft:end_stone_brick_slab
replaceitem entity @s[scores={aestd.block_id=637}] weapon minecraft:smooth_sandstone_slab
replaceitem entity @s[scores={aestd.block_id=638}] weapon minecraft:smooth_quartz_slab
replaceitem entity @s[scores={aestd.block_id=639}] weapon minecraft:granite_slab
