replaceitem entity @s[scores={aestd.block_id=640}] weapon minecraft:andesite_slab
replaceitem entity @s[scores={aestd.block_id=641}] weapon minecraft:red_nether_brick_slab
replaceitem entity @s[scores={aestd.block_id=642}] weapon minecraft:polished_andesite_slab
replaceitem entity @s[scores={aestd.block_id=643}] weapon minecraft:diorite_slab
replaceitem entity @s[scores={aestd.block_id=644}] weapon minecraft:brick_wall
replaceitem entity @s[scores={aestd.block_id=645}] weapon minecraft:prismarine_wall
replaceitem entity @s[scores={aestd.block_id=646}] weapon minecraft:red_sandstone_wall
replaceitem entity @s[scores={aestd.block_id=647}] weapon minecraft:mossy_stone_brick_wall
replaceitem entity @s[scores={aestd.block_id=648}] weapon minecraft:granite_wall
replaceitem entity @s[scores={aestd.block_id=649}] weapon minecraft:stone_brick_wall
replaceitem entity @s[scores={aestd.block_id=650}] weapon minecraft:nether_brick_wall
