replaceitem entity @s[scores={aestd.block_id=651}] weapon minecraft:andesite_wall
replaceitem entity @s[scores={aestd.block_id=652}] weapon minecraft:red_nether_brick_wall
replaceitem entity @s[scores={aestd.block_id=653}] weapon minecraft:sandstone_wall
replaceitem entity @s[scores={aestd.block_id=654}] weapon minecraft:end_stone_brick_wall
replaceitem entity @s[scores={aestd.block_id=655}] weapon minecraft:diorite_wall
replaceitem entity @s[scores={aestd.block_id=656}] weapon minecraft:scaffolding
replaceitem entity @s[scores={aestd.block_id=657}] weapon minecraft:loom
replaceitem entity @s[scores={aestd.block_id=658}] weapon minecraft:barrel
replaceitem entity @s[scores={aestd.block_id=659}] weapon minecraft:smoker
replaceitem entity @s[scores={aestd.block_id=660}] weapon minecraft:blast_furnace
