replaceitem entity @s[scores={aestd.block_id=661}] weapon minecraft:cartography_table
replaceitem entity @s[scores={aestd.block_id=662}] weapon minecraft:fletching_table
replaceitem entity @s[scores={aestd.block_id=663}] weapon minecraft:grindstone
replaceitem entity @s[scores={aestd.block_id=664}] weapon minecraft:lectern
replaceitem entity @s[scores={aestd.block_id=665}] weapon minecraft:smithing_table
replaceitem entity @s[scores={aestd.block_id=666}] weapon minecraft:stonecutter
replaceitem entity @s[scores={aestd.block_id=667}] weapon minecraft:bell
replaceitem entity @s[scores={aestd.block_id=668}] weapon minecraft:lantern
replaceitem entity @s[scores={aestd.block_id=669}] weapon minecraft:sweet_berries
replaceitem entity @s[scores={aestd.block_id=670}] weapon minecraft:structure_block
replaceitem entity @s[scores={aestd.block_id=671}] weapon minecraft:jigsaw
